//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Mỹ_Phẩm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        public Donhang()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
        }
    
        public int Madon { get; set; }
        public Nullable<System.DateTime> Ngaydat { get; set; }
        public Nullable<int> Tinhtrang { get; set; }
        public Nullable<int> MaNguoidung { get; set; }
    
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual Nguoidung Nguoidung { get; set; }
    }
}
