//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Mỹ_Phẩm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonhangOnl
    {
        public DonhangOnl()
        {
            this.ChitietdonhangOnls = new HashSet<ChitietdonhangOnl>();
        }
    
        public int Madon { get; set; }
        public Nullable<System.DateTime> Ngaydat { get; set; }
        public Nullable<System.DateTime> Ngaygiao { get; set; }
        public string Tinhtrang { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual ICollection<ChitietdonhangOnl> ChitietdonhangOnls { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
