//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Mỹ_Phẩm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoidung
    {
        public Nguoidung()
        {
            this.Donhangs = new HashSet<Donhang>();
        }
    
        public int MaNguoiDung { get; set; }
        public string Hoten { get; set; }
        public string Email { get; set; }
        public string Dienthoai { get; set; }
        public string Matkhau { get; set; }
        public Nullable<int> IDQuyen { get; set; }
        public string Diachi { get; set; }
    
        public virtual ICollection<Donhang> Donhangs { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
