//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Mỹ_Phẩm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCC
    {
        public NhaCC()
        {
            this.LoHangs = new HashSet<LoHang>();
        }
    
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
    
        public virtual ICollection<LoHang> LoHangs { get; set; }
    }
}
