//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Mỹ_Phẩm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgaySing { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
