//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Mỹ_Phẩm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_MyPham_DAEntities3 : DbContext
    {
        public QL_MyPham_DAEntities3()
            : base("name=QL_MyPham_DAEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChitietdonhangOnl> ChitietdonhangOnls { get; set; }
        public DbSet<CTDonHang> CTDonHangs { get; set; }
        public DbSet<DonHang> DonHangs { get; set; }
        public DbSet<DonhangOnl> DonhangOnls { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<KhuyenMai> KhuyenMais { get; set; }
        public DbSet<LoaiHang> LoaiHangs { get; set; }
        public DbSet<LoHang> LoHangs { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<NhaCC> NhaCCs { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<QUYEN> QUYENs { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public DbSet<ThuongHieu> ThuongHieux { get; set; }
    }
}
