//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Mỹ_Phẩm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN
    {
        public QUYEN()
        {
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public int iMaQuyen { get; set; }
        public string sTenQuyen { get; set; }
    
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
