//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Mỹ_Phẩm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChitietdonhangOnls = new HashSet<ChitietdonhangOnl>();
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.LoHangs = new HashSet<LoHang>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaLoai { get; set; }
        public string MaKM { get; set; }
        public string MaTH { get; set; }
        public Nullable<System.DateTime> HSD { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string MoTa { get; set; }

        public decimal? iKHuyenMai()
        {

            if (KhuyenMai != null)
            {
                int? km = KhuyenMai.TenKM;
                return GiaBan - GiaBan * km / 100;
            }
            else
            {
                return GiaBan;
            }
                
                            
        }
        public int? tenKMNull()
        {
            KhuyenMai tenKM = new KhuyenMai();
            if (KhuyenMai != null)
            {
                return KhuyenMai.TenKM;
            }
            else if(KhuyenMai == null)
            {
               
                tenKM.TenKM = 0;
            }
            return tenKM.TenKM;
        }

        public virtual ICollection<ChitietdonhangOnl> ChitietdonhangOnls { get; set; }
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
        public virtual ICollection<LoHang> LoHangs { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
