//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bán_Mỹ_Phẩm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuonghieu
    {
        public Thuonghieu()
        {
            this.Sanphams = new HashSet<Sanpham>();
        }
    
        public int Math { get; set; }
        public string Tenth { get; set; }
    
        public virtual ICollection<Sanpham> Sanphams { get; set; }
    }
}
